# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auction-svc
  namespace: backend
  labels:
    app: auction-svc
spec:
  selector:
    matchLabels:
      app: auction-svc
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: auction-svc
    spec:
      initContainers:
      - name: wait-for-postgres
        image: busybox:1.36
        command:
          - sh
          - -c
          - |
            echo "Waiting for Postgres..."
            until nc -z postgres-clusterip.backend.svc.cluster.local 5432; do
              echo "Postgres not ready, sleeping 5s..."
              sleep 5
            done
            echo "Postgres is ready!"
      containers:
        - name: auction-svc
          image: nguyenthanh/auctions-svc
          imagePullPolicy: Never
          env:
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef: 
                  name: auction-secret
                  key: connString
            - name: RabbitMQ__Username
              valueFrom:
                secretKeyRef: 
                  name: rabbit-secret
                  key: username 
            - name: RabbitMQ__Password
              valueFrom:
                secretKeyRef:
                  name: rabbit-secret
                  key: password
          envFrom:
            - configMapRef:
                name: auction-svc-config
          ports:
            - containerPort: 80
              name: web
            - containerPort: 7777
              name: grpc
---
# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: auction-clusterip
  namespace: backend
spec:
  selector:
    app: auction-svc #tro dung container
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      name: web
    - port: 7777
      targetPort: 7777
      name: grpc
---