# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: buyings-svc
  namespace: backend
  labels:
    app: buyings-svc
spec:
  selector:
    matchLabels:
      app: buyings-svc
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: buyings-svc
    spec:
      containers:
        - name: buyings-svc
          image: nguyenthanh/buyings-svc
          imagePullPolicy: Never
          env: 
            - name: ConnectionStrings__BuyingDbConnection
              valueFrom:
                secretKeyRef:
                  name: buying-secret
                  key: connString 
            - name: RabbitMQ__Username
              valueFrom:
                secretKeyRef: 
                  name: rabbit-secret
                  key: username 
            - name: RabbitMQ__Password
              valueFrom:
                secretKeyRef:
                  name: rabbit-secret
                  key: password
          envFrom:
            - configMapRef:
                name: buyings-svc-config
          ports:
            - containerPort: 80
              name: web

---
# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: buyings-clusterip
  namespace: backend
spec:
  selector:
    app: buyings-svc #tro dung container
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      name: web
---